// Automatically generated by astro-icon
// edc3baa769d6a2a12337e123b59ee5ae9e98788a5e7fbbf66465b13c69c9bbc0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "facebook"
		| "instagram"
		| "mano"
		| "phone"
		| "youtube";
}